# Generated by Django 2.2 on 2019-06-17 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_testscores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testscores',
            name='max_watts',
            field=models.FloatField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='testscores',
            name='six_k',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='testscores',
            name='two_k',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
    ]
